<H1><B>01 Data Collection</B></H1>

<H3><B>Step 1</B>&nbsp;&nbsp;&nbsp;Connect to website, find data</H3>
Inormation given by professor Jeroen: Op een fictieve site van het Medisch Centrum Randstad vinden jullie de data van gegenereerde
gegevens betreffende levensstijl en levensverwachting. Aan jullie de taak om deze data te scrapen.<br>&nbsp; <i>This paragraph still needs attention and explanation how we obtained data in which way.</i>

<H3><B>Step 2</B>&nbsp;&nbsp;&nbsp;Save DATA to suitable location.</H3><i>With advice from Jeroen we understood temporary data is stored locally on your drive after analyzing DataFrame online.</i><br>Find temporary DATA in '\Project\rest_server\medisch_centrum_randstad\db.sqlite3' (depending on your USER location).<br>&nbsp;

<H3><B>Step 3</B>&nbsp;&nbsp;&nbsp;Import data into SQLite and EXPORT DATA as CSV</H3>
Import <B>scraped data (file 'db.sqlite3')</B> into DB Browser for SQLite. <br>Find data from 'Tables/rest_api_netlify' and EXPORT DATA as CSV.<br>&nbsp;

In [5]:
from PIL import Image
import csv
import json
import os

import pandas as pd
import sqlite3

import matplotlib.pyplot as plt
import numpy as np
import scipy as cp

In [11]:
import pandas as pd
df = pd.DataFrame()
# Data inlezen
df = pd.read_csv('../../Project/data1.csv')
display(df)

df.columns[1]
# display(df['genetic'])   # Age is variable and usable.
display(df.genetic)      # 'Hard-Coded: short version of previous. Same output.
# type(df['genetic'])        # pandas.core.series.Series

# NOTE: This DataFrame uses 'genetic' for 'age'.

,id,genetic,length,mass,exercise,smoking,alcohol,lifespan,sugar
0,1,73.9,185.0,99.7,0.9,0.0,2.4,73.1,6.9
1,2,86.0,172.0,105.4,1.8,8.1,0.4,85.0,4.2
2,3,83.3,176.0,111.4,1.1,0.8,4.6,81.6,7.5
3,4,82.8,164.0,111.4,4.7,11.8,1.0,81.0,2.9
4,5,78.7,178.0,71.6,1.5,8.3,4.9,75.0,5.5
...,...,...,...,...,...,...,...,...,...
4091,4092,80.3,176.0,115.9,3.7,0.1,5.6,80.7,5.8
4092,4093,75.3,162.0,129.6,3.6,6.2,5.6,71.1,7.6
4093,4094,93.1,189.0,115.3,2.7,9.4,4.9,90.0,6.6
4094,4095,77.9,170.0,90.8,2.3,13.2,0.8,75.9,6.2
4095,4096,101.3,188.0,129.2,1.2,8.2,6.0,96.9,6.2

0        73.9
1        86.0
2        83.3
3        82.8
4        78.7
        ...
4091     80.3
4092     75.3
4093     93.1
4094     77.9
4095    101.3
Name: genetic, Length: 4096, dtype: float64

&nbsp;<br><H3><B>Step 3</B>   Think about process to automate the above.</H3><i>This paragraph still needs attention and explanation.</i>